#!/bin/bash -ex

groupadd -f -g $GROUP_ID $GROUP_NAME
useradd -m -d /home/build -g $GROUP_NAME -u $USER_ID $USER_NAME -s "/bin/bash"

if [[ -n "$REPO_NAME" ]]; then
    echo "[$REPO_NAME]" >> /etc/pacman.conf 
    echo "Server = $REPO" >> /etc/pacman.conf
    echo "SigLevel = $REPO_SIG" >> /etc/pacman.conf
fi

pacman -Syyu --noconfirm --noprogressbar

cd /home/build
chown -R $USER_NAME:$GROUP_NAME /home/build
sudo -u $USER_NAME makepkg --noprogressbar --nosign --syncdeps --noconfirm --force
