#!/usr/bin/bash -ex

groupadd -f -g $GROUP_ID $GROUP_NAME
useradd -m -d /home/build -g $GROUP_NAME -u $USER_ID $USER_NAME -s "/usr/bin/bash"

if [[ -n "$REPO_NAME" ]]; then
    echo "[$REPO_NAME]" >> /etc/pacman.conf 
    echo "Server = $REPO" >> /etc/pacman.conf
    echo "SigLevel = $REPO_SIG" >> /etc/pacman.conf
fi

pacman -Syyu --noconfirm --noprogressbar

cd /home/build

mkdir .gnupg
echo "keyserver-options auto-key-retrieve" > .gnupg/gpg.conf
echo "auto-key-locate hkp://pool.sks-keyservers.net" >> .gnupg/gpg.conf

chown -R $USER_NAME:$GROUP_NAME /home/build
sudo -u $USER_NAME makepkg --noprogressbar --nosign --syncdeps --noconfirm --force
