#!/bin/bash -ex

pacman -Syyu --force --noconfirm --needed --noprogressbar base-devel
pacman -Scc --noconfirm 
mkdir -p /home/build 
chmod 755 /usr/bin/build_package 
echo "ALL ALL=(ALL) NOPASSWD: /usr/bin/pacman" >> /etc/sudoers
