#!/bin/bash -ex

/sbin/get-new-mirrors

pacman -Syyu --noconfirm --needed --noprogressbar base-devel bash sudo
pacman -Scc --noconfirm 

mkdir -p /home/build 
chmod 755 /usr/bin/build_package 

# Allow build user to install dependencies
echo "ALL ALL=(ALL) NOPASSWD: /usr/bin/pacman" >> /etc/sudoers

# Change shell to bash, some packages don't build with zsh
rm /usr/bin/sh
ln -s /usr/bin/bash /usr/bin/sh

# Enable multilib
echo "[multilib]" >> /etc/pacman.conf
echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf


